/**
 * PWA manifest, served at /manifest.webmanifest.
 *
 * Generated by Next's file convention rather than dropped in `public/` — that
 * keeps it typed, lets it read from the same place the metadata does, and makes
 * a missing-file 404 structurally impossible.
 */
export default function manifest() {
  return {
    name: 'DairyDrop',
    short_name: 'DairyDrop',
    description: 'Daily milk delivery, managed.',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#fafaf9',
    theme_color: '#059669',
    categories: ['food', 'shopping', 'business'],
    icons: [
      { src: '/icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
      { src: '/icon-maskable.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'maskable' },
    ],
  };
}
