/**
 * PWA manifest, served at /manifest.webmanifest.
 *
 * Generated by Next's file convention rather than dropped in `public/` — that
 * keeps it typed, lets it read from the same place the metadata does, and makes
 * a missing-file 404 structurally impossible.
 */
export default function manifest() {
  return {
    name: 'DairyDrop',
    short_name: 'DairyDrop',
    description: 'Daily milk delivery, managed.',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#fafcff',
    theme_color: '#2563eb',
    categories: ['food', 'shopping', 'business'],
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icon-maskable-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: '/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
